# Generated by Django 2.1.3 on 2018-12-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
