# Generated by Django 2.1.3 on 2018-12-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0002_flight_booked'),
        ('ticket', '0003_auto_20181215_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Passport')),
                ('contact_address', models.CharField(max_length=255, verbose_name='Address')),
                ('contact_kin_name', models.CharField(max_length=255, verbose_name='NOK Name')),
                ('contact_kin_relationship', models.CharField(max_length=255, verbose_name='Relationship')),
                ('contact_kin_phone', models.CharField(max_length=255, verbose_name='NOK Phone')),
                ('contact_kin_email', models.CharField(max_length=255, verbose_name='NOK E-mail')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight', to='flight.Flight')),
            ],
        ),
    ]
