# Generated by Django 2.1.3 on 2018-12-12 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_date', models.DateTimeField(verbose_name='Depart Date')),
                ('return_date', models.DateTimeField(verbose_name='Return Date')),
                ('departure', models.CharField(max_length=100, verbose_name='Departure')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('fare', models.IntegerField(choices=[(0, 'One-Way'), (1, 'Round-Trip')], verbose_name='Fare')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
