# Generated by Django 2.1.3 on 2018-12-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
