# Generated by Django 2.1.3 on 2018-12-23 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='reminder_notification_sent_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 17, 7, 26, 959823, tzinfo=utc), verbose_name='Reminder notification sent at'),
            preserve_default=False,
        ),
    ]
