# Generated by Django 2.1.3 on 2018-12-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport'),
        ),
    ]
